name: Rails CI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: realyou_test
          POSTGRES_HOST: localhhost
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install rbenv
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev

      - name: Set up rbenv and install Ruby 3.0.0
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init --no-rehash -)"' >> ~/.bashrc
          exec $SHELL
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          rbenv install 3.0.0
          echo "Ruby Version: $( -v)"
          rbenv global 3.0.0

      - name: Install Dependencies
        run: |
          gem install bundler --user-install
          export GEM_HOME=$HOME/.gem
          export PATH=$GEM_HOME/bin:$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH
          bundle install --path $GEM_HOME


      - name: Database setup
        run: |
          export GEM_HOME="$HOME/.gem"
          export PATH="$GEM_HOME/bin:$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
          export POSTGRES_USER="postgres"
          export POSTGRES_PASSWORD="postgres"
          export POSTGRES_DB="realyou_test"
          $GEM_HOME/bin/bundle exec rails db:create
          $GEM_HOME/bin/bundle exec rails db:migrate

      - name: Run Tests
        run: |
          export GEM_HOME=$HOME/.gem
          export PATH=$GEM_HOME/bin:$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH
          $GEM_HOME/bin/bundle exec rspec